object Config {
    const val compileSdk = 33
    const val targetSdk = 33
    const val minSdk = 22

    const val buildTools = "30.0.3"

    const val appVersion = "1.16.1"

    const val appVersionApplicant = "1.0"
}

object Versions {
    const val kotlin = "1.7.10"
    const val gradle = "7.3.0"
    const val glide = "4.13.2"
    const val glideCompiler = "4.12.0"
    const val threetenabp = "1.3.1"
    const val timber = "4.7.1"
    const val firefoxBom = "26.2.0"
    const val activityKtx = "1.6.0"
    const val fragmentKtx = "1.5.3"
    const val lifecycleExt = "2.2.0"
    const val lifecycleKtx = "2.5.1"
    const val swiperefreshlayout = "1.1.0"
    const val zxingCore = "3.3.3"
    const val zxingEmbedded = "3.2.0@aar"
    const val prettytime = "5.0.1.Final"
    const val stfalcon = "1.0.1"
    const val coreKtx = "1.9.0"
    const val appcompat = "1.5.1"
    const val material = "1.6.1"
    const val joda = "2.10.9.1"
    const val paging = "3.1.1"
    const val konfetti = "2.0.2"
    const val lottie = "5.1.1"
    const val browser = "1.4.0"
    const val flexbox = "2.0.1"
    const val mimeTypes = "0.1.3"
    const val coroutines = "1.6.1"
    const val recycler = "1.2.1"
    const val constraint = "2.1.4"
    const val dagger = "2.42"
}

object Deps {
    const val gradle = "com.android.tools.build:gradle:${Versions.gradle}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.glideCompiler}"
    const val threetenabp = "com.jakewharton.threetenabp:threetenabp:${Versions.threetenabp}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val firefoxBom = "com.google.firebase:firebase-bom:${Versions.firefoxBom}"
    const val firebaseAnalytics = "com.google.firebase:firebase-analytics-ktx"
    const val firebaseCrashlytics = "com.google.firebase:firebase-crashlytics-ktx"
    const val activityKtx = "androidx.activity:activity-ktx:${Versions.activityKtx}"
    const val fragmentKtx = "androidx.fragment:fragment-ktx:${Versions.fragmentKtx}"
    const val lifecycleExt = "androidx.lifecycle:lifecycle-extensions:${Versions.lifecycleExt}"
    const val lifecycleLivedataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.lifecycleKtx}"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycleKtx}"
    const val swiperefreshlayout = "androidx.swiperefreshlayout:swiperefreshlayout:${Versions.swiperefreshlayout}"
    const val zxingCore = "com.google.zxing:core:${Versions.zxingCore}"
    const val zxingEmbedded = "com.journeyapps:zxing-android-embedded:${Versions.zxingEmbedded}"
    const val prettytime = "org.ocpsoft.prettytime:prettytime:${Versions.prettytime}"
    const val stfalcon = "com.github.stfalcon:stfalcon-imageviewer:${Versions.stfalcon}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val joda = "net.danlew:android.joda:${Versions.joda}"
    const val paging = "androidx.paging:paging-runtime-ktx:${Versions.paging}"
    const val konfetti = "nl.dionsegijn:konfetti-xml:${Versions.konfetti}"
    const val lottie = "com.airbnb.android:lottie:${Versions.lottie}"
    const val browser = "androidx.browser:browser:${Versions.browser}"
    const val flexbox = "com.google.android:flexbox:${Versions.flexbox}"
    const val mimeTypes = "org.overviewproject:mime-types:${Versions.mimeTypes}"
    const val coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutines}"
    const val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutines}"
    const val recycler = "androidx.recyclerview:recyclerview:${Versions.recycler}"
    const val constraint = "androidx.constraintlayout:constraintlayout:${Versions.constraint}"
    const val kotlinGradle = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
}